# Generated by Django 5.2.12 on 2026-08-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='certificate_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
